server:
  port: 8080

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: root

mybatis:
  mapper-locations: mappers/**.xml
  type-aliases-package: com.dome.pojo
  configuration:
    map-underscore-to-camel-case: true

str:
  abc: 123
  zxc: 456
